info:
  spring:
    profiles: ${spring.profiles.active:default}

spring:
  jpa:
    hibernate:
      ddl_auto: none
  security:
    oauth2:
      client:
        registration:
          github:
            # GitHub OAuth application credentials for use when logging into administrative
            # console at /admin. Default 'id' and 'secret' values apply only when running
            # locally, i.e. at http://localhost:8080. Production values must be overridden
            # using SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID and
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET, respectively.
            client-id: fb06c006c2ed62fe9e8b
            client-secret: 164264e3f6d70c7c21713b7fa64225cb8d6107b2
            # Request the 'read: org' OAuth scope, so that we can check whether the
            # authenticated user belongs to the configured `sagan.site.github.team` for
            # admin access.
            scope:
             - 'read:org'

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health, info

sagan:
  site:
    github:
      # Credentials are based on users belonging to a particular GitHub team,
      # by requesting the GitHub API (see github.client configuration keys).
      # This key can be found in the list of teams in your organization
      # See http://developer.github.com/v3/orgs/teams/#list-teams
      org: spring-io
      team: spring-team
---

spring:
  config:
    activate:
      on-profile: cloud
  web:
    resources:
      chain:
        cache: true
        strategy:
          content:
            enabled: true
      cache:
        cachecontrol:
          max-age: 7d
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json
  forward-headers-strategy: native

---

spring:
  config:
    activate:
      on-profile: standalone
  datasource:
    url: jdbc:h2:mem:sagan;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  flyway:
    locations: classpath:/db/migration, classpath:/db/dev
  devtools:
    restart:
      additional_paths:
        - ../sagan-client/build/dist/
      additional_exclude: "css/**,fonts/**,images/**,js/**,icon*.png,manifest.json,robots.txt"
  web:
    resources:
      static-locations:
        - file:../sagan-client/build/dist/
        - file:./sagan-client/build/dist/
        - file:./build/asciidoc/
        - file:./sagan-site/build/asciidoc/
        - classpath:/public/
---

spring:
  config:
    activate:
      on-profile: staging
sagan:
  site:
    renderer:
      service-url: https://springio-renderer-dev.sc2-04-pcf1-apps.oc.vmware.com/
    disqus:
      short-name: spring-io-staging
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    hikari:
      maximum-pool-size: 8
sagan:
  site:
    disqus:
      short-name: spring-io
