---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: bellsoft/liberica-openjdk-debian
    tag: 11
inputs:
- name: sagan-renderer-repo
outputs:
- name: build
caches:
- path: gradle
run:
  path: /bin/bash
  args:
  - -ec
  - |
    ${PWD}/sagan-renderer-repo/concourse/scripts/build-sagan-renderer.sh