---
applications:
- name: springio
  buildpacks:
  - https://github.com/cloudfoundry/java-buildpack.git
  instances: 3
  health-check-type: http
  health-check-http-endpoint: /actuator/health/liveness
  timeout: 30
  memory: 2048M
  disk_quota: 1024M
  routes:
  - route: spring.io
  - route: https://springio.sc2-04-pcf1-apps.oc.vmware.com
  services:
  - logz-springio
  - springio-db
  - springio-cache
