server:
  port: 8082
  servlet:
    session:
      timeout: -1

spring:
  application:
    name: control-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

broker:
  relay:
    host: ${activemq.host:10.132.0.8}
    user: admin
    password:
  url: tcp://${activemq.host:10.132.0.8}:61616
  queue: actions.queue
  topic: actions.topic

logging:
  level:
    org.springframework.messaging: debug

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:10.132.0.2}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}