package meet_eat.server.service;

import meet_eat.data.entity.user.Email;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@RunWith(SpringRunner.class)
@SpringBootTest
public class EmailServiceTest {

    private static final Email EMAIL_SENDER = new Email("noreply.meet.eat@gmail.com");
    private static final Email EMAIL_RECIPIENT = new Email("noreply.meet.eat@gmail.com");
    private static final String EMAIL_SUBJECT = "JUnit";

    @Autowired
    private EmailService emailService;

    @Test
    public void testSendMailValid() {
        // Test data
        String dateText = LocalDateTime.now().format(DateTimeFormatter.ofPattern("d MMMM yyyy HH-mm-ss"));
        String text = "Dear developer,\n\rThis test mail was generated by jUnit.\n\rTime of creation: " + dateText;

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, EMAIL_SUBJECT, text);
    }

    @Test
    public void testSendMailEmptyText() {
        // Test data
        String text = "";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, EMAIL_SUBJECT, text);
    }

    @Test
    public void testSendMailEmptySubject() {
        // Test data
        String subject = "";
        String text = "JUnit";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, subject, text);
    }

    @Test
    public void testSendMailEmptySubjectAndEmptyText() {
        // Test data
        String subject = "";
        String text = "";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, subject, text);
    }

    @Test(expected = NullPointerException.class)
    public void testSendMailNullRecipient() {
        // Test data
        String subject = "Mail by jUnit";
        String text = "TestMail";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, null, subject, text);
    }

    @Test(expected = NullPointerException.class)
    public void testSendMailNullSender() {
        // Test data
        String subject = "Mail by jUnit";
        String text = "TestMail";

        // Execution
        emailService.sendEmail(null, EMAIL_RECIPIENT, subject, text);
    }

    @Test(expected = NullPointerException.class)
    public void testSendMailNullSubject() {
        // Test data
        String text = "TestMail";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, null, text);
    }

    @Test(expected = NullPointerException.class)
    public void testSendMailNullText() {
        // Test data
        String subject = "Mail by jUnit";

        // Execution
        emailService.sendEmail(EMAIL_SENDER, EMAIL_RECIPIENT, subject, null);
    }
}
