version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    tty:
      true

  weatherbackend:
    build: ./weatherbackend
    depends_on:
    - rabbitmq
    ports:
      - "8090"
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "LOGSTASH_HOST=host.docker.internal"
    tty:
      true
    restart:
      unless-stopped

