version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      esdanet:
  kafka:
    image: wurstmeister/kafka
    networks:
      esdanet:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "advice-topic:1:1,advice-topicx:1:1"
    
networks:
    esdanet: