server:
  port: 8000

eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: device-management-ms
          uri: lb://device-management-service
          predicates:
            - Path=/device-management-service/**
          filters:
            - StripPrefix=1
        - id: control-ms
          uri: lb://control-service
          predicates:
            - Path=/control-service/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["*"]
            allowedMethods: ["*"]
            allowedHeaders: "*"
            allowCredentials: true