name: Quality Control

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  verify:
    name: Maven Verify
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run Maven
      run: mvn -B -U clean verify

  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
        fail-fast: false
    - name: Autobuild Repository
      uses: github/codeql-action/autobuild@v2
    - name: Perform Analyze
      uses: github/codeql-action/analyze@v2
