name: Release to Sonatype

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clean up for release
        working-directory: ./
        run: |
          rm -rf ./.mvn
          rm -f ./pom.xml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Build with Maven
        working-directory: ./maven
        run: mvn -B -U clean package --file pom.xml

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        working-directory: ./maven
        run: mvn -Plocal-build-deployable deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
